# Generated by Django 3.2.8 on 2021-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(verbose_name='Ссылка на репозиторий'),
        ),
    ]
