# Generated by Django 3.2.8 on 2021-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_url_project_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='closed',
        ),
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Заметка активна'),
        ),
    ]
