# Generated by Django 3.2.8 on 2021-12-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['pk'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
