# Generated by Django 3.2.8 on 2021-12-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_auto_20211112_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['pk'], 'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pk'], 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
